spring.application.name=biblioteca

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://iamthiagohenry8_db_user:YjGaI4jXv6CkwaBK@sgb.tsmmfel.mongodb.net/biblioteca?retryWrites=true&w=majority&appName=SGB

# Porta
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false